version: '3'

services:
  nginx:
    image: nginx
    volumes:
      - './assets/build:/usr/share/nginx/html'
    ports:
      - "${CHAT_APP_PORT}:80"

  message-service:
    build: ./api/message-service
    container_name: message-service
    volumes:
      - './api/message-service:/app'
    ports:
      - "${MESSAGE_SERVICE_PORT}:5000"
